NIFI-15364 Fixed QUIC NoClassDefFoundError for Azure Parameter Provider (#10663)
Signed-off-by: David Handermann <exceptionfactory@apache.org>
(cherry picked from commit d744ccb671e40c0a73a77b2af5f6e5934c5ace41)